<?php

namespace AppBundle\Repository;

/**
 * CompetenciaConductualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenciaConductualRepository extends \Doctrine\ORM\EntityRepository
{
}
