<?php

namespace AppBundle\Repository;

/**
 * PerfilCompetenciaConductualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilCompetenciaConductualRepository extends \Doctrine\ORM\EntityRepository
{
}
